export const STORIES = [
    {
      id: "1",
      username: "john.doe",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
    {
      id: "2",
      username: "sarah.k",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
    {
      id: "3",
      username: "michael.scott",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: false,
    },
    {
      id: "4",
      username: "pam.beesly",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
    {
      id: "5",
      username: "jim.halpert",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: false,
    },
    {
      id: "6",
      username: "dwight.schrute",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
    {
      id: "7",
      username: "angela.martin",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: false,
    },
    {
      id: "8",
      username: "kevin.malone",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
    {
      id: "9",
      username: "oscar.martinez",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: false,
    },
    {
      id: "10",
      username: "toby.flenderson",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
    {
      id: "11",
      username: "kelly.kapoor",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
    {
      id: "12",
      username: "ryan.howard",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: false,
    },
    {
      id: "13",
      username: "stanley.hudson",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
    {
      id: "14",
      username: "phyllis.vance",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: false,
    },
    {
      id: "15",
      username: "meredith.palmer",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
    {
      id: "16",
      username: "andy.bernard",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: false,
    },
    {
      id: "17",
      username: "creed.bratton",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
    {
      id: "18",
      username: "erin.hannon",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
    {
      id: "19",
      username: "darryl.philbin",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: false,
    },
    {
      id: "20",
      username: "jan.levinson",
      avatar: "https://img.freepik.com/free-vector/isolated-young-handsome-man-different-poses-white-background-illustration_632498-859.jpg?semt=ais_hybrid",
      hasStory: true,
    },
  ];